# Local pcms only: the inferno pcms ship in /etc/alsa/conf.d/60-inferno.conf
# (inferno package).

pcm.speaker {
	type plug
	slave.pcm {
		type hw
		card Headphones
		device 0
	}
	hint {
		show on
		description "Onboard analog jack (3.5mm)"
	}
}

