#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org
# Adapted for Buildroot: no mount_root, no /etc/diag.sh (board LED support).

START=95

boot() {
	rm -f /sysupgrade.tgz && sync

	# process user commands
	[ -f /etc/rc.local ] && {
		sh /etc/rc.local
	}
}
