#!/bin/sh /etc/rc.common
# ptp-monitor: ucode daemon bridging statime's usrvclock export to ubus and
# camilladsp supervision (start on PTP lock, stop on clock loss).

START=80
STOP=24
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/ucode /usr/bin/ptp-monitor
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
